version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2021-01-01 by month" --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv
  
  generate_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output/measures
      needs: [generate_study_population]
      outputs:
        moderately_sensitive:
          measure_csv: output/measures/measure_*.csv

  generate_plots:
    run: python:latest python analysis/generate_plots.py
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        figure1: output/figures/population_rates.jpeg
        figure2: output/figures/sex_rates.jpeg
        figure3: output/figures/region_rates.jpeg
        figure4: output/figures/age_rates.jpeg
  
 
  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/pulse_oximetry.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        notebook: output/pulse_oximetry.html